name: visora_ai
description: Visora â€“ Ultimate AI Video Studio
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  file_picker: ^8.0.0+1
  image_picker: ^1.0.4
  lottie: ^3.1.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^5.1.0
  image: ^4.2.0
  blur: ^3.1.0
  url_launcher: ^6.2.4
  path_provider: ^2.1.3
  web_socket_channel: ^2.4.0
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.3
  firebase_analytics: ^11.2.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  json_annotation: ^4.9.0
  video_player: ^2.8.6
  cached_network_image: ^3.3.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/loading.json
    - assets/lottie/done.json
    - assets/logo/visora_logo.png
    - assets/logo/visora_logo_splash.png
    - assets/logo/visora_logo_white.png
    - assets/logo/visora_logo_dark.png
    - assets/logo/visora_full_text.png
    - assets/logo/visora_brand_banner.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/visora_logo.png"
